<a href="https://colab.research.google.com/github/Emaperidol/Learning-Coding/blob/main/Mosleh_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment **01**

### 1
Assign a=10 and b=20. Print the result for (a+b)^2/(a-b)

In [ ]:
a=10
b=20
F"{(a+b)**2/(a-b)}"

'-90.0'

### 2

In [ ]:
S = "What you are you do not see, what you see is your shadow"
len(S)

56

In [ ]:
S_array = S.split()
S_array[0] == "What"

True

In [ ]:
S_array[-1] == "shadow"

True

In [ ]:
S_array.index("see")

9

In [ ]:
for i, word in enumerate(S_array):
  if word == "you":
    S_array[i] = "I"
  if word == "your":
    S_array[i] = "my"
  if word == "are":
    S_array[i] = "am"

print(S_array)

['What', 'I', 'am', 'I', 'do', 'not', 'see,', 'what', 'I', 'see', 'is', 'my', 'shadow']


In [ ]:
S_array = S.split()
print(S_array)

['What', 'you', 'are', 'you', 'do', 'not', 'see,', 'what', 'you', 'see', 'is', 'your', 'shadow']


In [ ]:
S_upper = S.upper()
print(S_upper)

WHAT YOU ARE YOU DO NOT SEE, WHAT YOU SEE IS YOUR SHADOW


In [ ]:
S_lower = S.lower()
print(S_lower)

what you are you do not see, what you see is your shadow


In [ ]:
count_y = S.count("y")
print(count_y)

4


In [ ]:
S_cleaned = S.strip()
print(S_cleaned)

What you are you do not see, what you see is your shadow


### 3

In [ ]:
uno = "-100"
i = -int(uno)
print(i)

100


In [ ]:
tres = "3.25"
f = float(tres)
print(f)

3.25


### 4

In [ ]:
l = [-1,2,3,5,10]
l.reverse()
print(l)

[10, 5, 3, 2, -1]


In [ ]:
l = [-2,4,5,9,-100]
l_squared = [num**2 for num in l]
print(l_squared)

[4, 16, 25, 81, 10000]


In [ ]:
l = [1,2,[-300,-100,[1000,200],400],3,-40]
l[2][2].append(-5000)
print(l)

[1, 2, [-300, -100, [1000, 200, -5000], 400], 3, -40]


In [ ]:
l = ["To","be","or","not","to","be"]
l_string = " ".join(l)
print(l_string)

To be or not to be


In [ ]:
number_list = [1,2,3]
str_list = ["one", "two", "three"]
zipped_list = list(zip(number_list,str_list))
print(zipped_list)

[(1, 'one'), (2, 'two'), (3, 'three')]


In [ ]:
my_list = [2*n for n in range(10)]
print(my_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


### 5

In [ ]:
squares_dict = {i: i**2 for i in range(1, 11)}
print(squares_dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
keys = ['One', 'Two', 'Three']
values = [1, 2, 3]
my_dict = dict(zip(keys, values))
print(my_dict)

{'One': 1, 'Two': 2, 'Three': 3}


### 6

In [ ]:
def sum_nums(my_list):
    return sum(my_list)

my_list = [1,1,2,3,5,8]
sum_nums(my_list)

20

### 7

In [ ]:
def count_case(S):
    upper_count = sum(1 for char in S if char.isupper())
    lower_count = sum(1 for char in S if char.islower())
    print(f"Number of upper case charactes: {upper_count}")
    print(f"Number of lower case charactes: {lower_count}")

S = "To sleep or not to sleep"
count_case(S)

Number of upper case charactes: 1
Number of lower case charactes: 18


### 8

In [ ]:
grade = int(input("Enter your score: "))
if grade >= 60:
    print('Congratulations! You have passed the course.')
else:
    print('Sorry, you did not pass the course.')

Enter your score: 34
Sorry, you did not pass the course.


### 9

In [ ]:
for i in range(100, 3001):
    if i % 11 == 0 and i % 7 == 0:
        print(i)

154
231
308
385
462
539
616
693
770
847
924
1001
1078
1155
1232
1309
1386
1463
1540
1617
1694
1771
1848
1925
2002
2079
2156
2233
2310
2387
2464
2541
2618
2695
2772
2849
2926


### 10

In [ ]:
def fruit_namer(lst):
    new_lst = [fruit for fruit in lst if fruit != ""]
    return new_lst

l = ["apple", "banana", "", "grape"]
fruit_namer(l)

['apple', 'banana', 'grape']

### 11

In [ ]:
import numpy as np
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 12

In [ ]:
vector = np.arange(5, 36)
print(vector)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35]


### 13

In [ ]:
array = np.arange(1, 10).reshape(3, 3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 14

In [ ]:
array = np.random.uniform(0, 1, (10, 10))
print(array)
min_val, max_val = array.min(), array.max()
print(f"Min val: {min_val}; Max val: {max_val}")


[[0.26720614 0.86396024 0.04351376 0.66220024 0.39820447 0.57361767
  0.76982745 0.2103566  0.02481343 0.86208144]
 [0.9172867  0.29754484 0.22276487 0.61028082 0.52410061 0.25509748
  0.28198818 0.73711223 0.19575405 0.37043566]
 [0.51711132 0.98975429 0.85638059 0.44267117 0.87066458 0.88281928
  0.81587478 0.49231974 0.34160792 0.46053365]
 [0.02674375 0.42416042 0.12051707 0.66610507 0.36936358 0.7059764
  0.3367747  0.51482474 0.28647476 0.29083171]
 [0.84325754 0.44571535 0.88797515 0.02542464 0.99322911 0.34105746
  0.89730373 0.94092981 0.95220701 0.24960461]
 [0.65703339 0.37347833 0.15899904 0.51923957 0.84522125 0.72330572
  0.17309257 0.47320671 0.93345079 0.77330665]
 [0.07524835 0.45804831 0.56916466 0.34294809 0.60003237 0.50185639
  0.67096536 0.32306609 0.54165453 0.00461775]
 [0.6129341  0.14299009 0.33412907 0.53791256 0.68207861 0.00313923
  0.0567396  0.20105161 0.55642953 0.89289942]
 [0.83717673 0.51125928 0.89035393 0.55007158 0.64631112 0.42298606
  0.67755317 

### 15

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


### 16

In [ ]:
array1 = np.random.uniform(0,10,(5,3))
array2 = np.random.uniform(0,10,(3,3))
result = np.dot(array1,array2)
print(result)

[[ 46.02720166  52.0058571   90.10598227]
 [ 56.52652535  60.34415964 108.61659412]
 [ 57.79520831  57.39665598 113.47886481]
 [ 34.21218039  60.35187671  70.21887572]
 [ 20.97004625  24.69357156  43.61091304]]


### 17

In [ ]:
my_array = np.array([[-40,-20,100], [12,-5,-3], [5,99,-105]])
new_column = np.array([[10, 10, 10]])
my_array = np.delete(my_array, 1, 1)
my_array = np.insert(my_array, 1, new_column, 1)
print(my_array)

[[ -40   10  100]
 [  12   10   -3]
 [   5   10 -105]]


### 18

In [ ]:
my_array = np.zeros((8, 8))
print(my_array)
my_array[:, [0, -1]] = 1
my_array[[0, -1], :] = 1
print(my_array)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


### 19

In [ ]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
diffy = np.diff(x)
print(diffy)

[-2  3  3  3 -4  6  2 -9]


### 20

In [ ]:
angles = np.arange(0, 190, 10)
print(angles)

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180]
